# Generated by Django 5.0.3 on 2024-05-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
